apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: credit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-mysql
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting; sleep 3; done']
      containers:
        - name: backend
          image: mohamedelaazzaoui00/credit-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/python?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "mohamed12345"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: JWT_SECRET
              value: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
            - name: JWT_EXPIRATION
              value: "86400000"
            - name: ENCRYPTION_SECRET_KEY
              value: "MySecretKey12345MySecretKey12345"
            - name: CORS_ALLOWED_ORIGINS
              value: "http://51.107.90.200:30080,http://localhost:3000,http://localhost:5173"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: credit-app
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
