[master]
k8s-master ansible_host=51.107.90.200 ansible_user=azureuser ansible_ssh_private_key_file=/media/sf_ubunto/project-devops-CICD-main/Terraform/ssh_key/id_rsa
[worker]
k8s-worker ansible_host=51.107.91.169 ansible_user=azureuser ansible_ssh_private_key_file=/media/sf_ubunto/project-devops-CICD-main/Terraform/ssh_key/id_rsa
[k8s:children]
master
worker
[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'